version: "3.9"
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: custom-clickhouse-server
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_PASSWORD=custom_password
    volumes:
      - ./clickhouse:/var/lib/clickhouse/
      - ./logs:/var/log/clickhouse-server/
      # - ./etc:/etc/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
